# Generated by Django 2.0.3 on 2018-03-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='personas')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('procedimiento', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=100)),
                ('dificultad', models.CharField(max_length=10)),
                ('tiempo', models.TimeField(auto_now_add=True)),
                ('porciones', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='recetas')),
                ('publico', models.BooleanField()),
                ('costo', models.CharField(max_length=50)),
                ('publicacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.CharField(max_length=1)),
                ('cantidad_calificaciones', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaXPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Persona')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta')),
            ],
        ),
        migrations.CreateModel(
            name='SeguidoresXPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='inicio.Persona')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='inicio.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TagXReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='notificacion',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueno', to='inicio.Persona'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='persona_externa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externo', to='inicio.Persona'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Ingrediente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Persona'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta'),
        ),
    ]
