# Generated by Django 2.0.3 on 2018-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20180328_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.FileField(blank=True, upload_to='personas'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='notas',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
