# Generated by Django 2.0.3 on 2018-04-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20180406_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='url',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
