# Generated by Django 2.0.3 on 2018-04-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20180410_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='receta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inicio.Receta'),
        ),
    ]
