# Generated by Django 2.0.3 on 2018-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_tag_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='duracion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
