# Generated by Django 2.0.3 on 2018-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_receta_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
