# Generated by Django 2.0.3 on 2018-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20180414_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
    ]
