# Generated by Django 2.0.3 on 2018-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20180414_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='persona',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='notas',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='receta',
            name='procedimiento',
            field=models.TextField(max_length=5000),
        ),
    ]
