# Generated by Django 2.0.3 on 2018-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20180503_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
